INSERT INTO hospital.myapp_user (id,user_name, user_passwd) VALUES (2, 'admin','admin');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (1, 'Ortopedia', 'yangyang', '18060100208', '1');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (2, 'Quemaduras', 'Daniel', '17010760014', '2');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (3, 'Dermatologia', 'Maria', '18060300106', '3');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (4, 'Psiquiatrico', 'Ana', '18050300233', '4');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (5, 'Pediatria', 'Jose', '18030606017', '5');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (6, 'Urologia', 'Carmen', '18050300127', '6');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (7, 'Oftalmologia', 'Cristina', '18060100218', '7');
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (11, '0000', 'yangyang', 'M', '30', '18010600619', 'Responsable', 5);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (1, '1001', 'Jesus', 'M', '30', '18010600104', 'Responsable', 1);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (2, '1002', 'Miguel', 'M', '31', '18010300222', 'Responsable', 2);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (3, '1003', 'Carmen', 'F', '35', '18010300219', 'Responsable', 2);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (4, '1004', 'Pepe', 'M', '40', '18010100322', 'Responsable', 3);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (5, '1005', 'Angela', 'F', '42', '18010100222', 'Responsable', 1);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (6, '1006', 'Igor', 'M', '38', '17060300133', 'Responsable', 7);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (7, '1007', 'Daniel', 'M', '36', '17050800269', 'Responsable', 4);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (8, '1008', 'Lorena', 'F', '29', '17050200320', 'Responsable', 6);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (9, '1009', 'Jose', 'M', '31', '17040600106', 'Responsable', 2);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (10, '1010', 'Julio', 'M', '35', '17030300619', 'Responsable', 4);
INSERT INTO hospital.myapp_medicine (id, medicine_name, medicine_num) VALUES (1, 'Eritromicina', 300);
INSERT INTO hospital.myapp_medicine (id, medicine_name, medicine_num) VALUES (2, 'Penicilina', 500);
INSERT INTO hospital.myapp_medicine (id, medicine_name, medicine_num) VALUES (3, 'Cefalosporina', 300);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (1, '1', '', '', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (2, '2', '', '', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (3, '3', '', '', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (4, '4', '', '', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (5, '5', '', '', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (6, '1', '', '', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (7, '2', '', '', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (8, '3', '', '', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (9, '4', '', '', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (10, '5', '', '', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (11, '1', '', '', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (12, '2', '', '', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (13, '3', '', '', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (14, '4', '', '', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (15, '5', '', '', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (16, '1', '', '', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (17, '2', '', '', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (18, '3', '', '', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (19, '4', '', '', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (20, '5', '', '', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (21, '1', '', '', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (22, '2', '', '', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (23, '3', '', '', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (24, '4', '', '', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (25, '5', '', '', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (26, '1', '', '', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (27, '2', '', '', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (28, '3', '', '', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (29, '4', '', '', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (30, '5', '', '', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (31, '1', '', '', 7);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (32, '2', '', '', 7);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (33, '3', '', '', 7);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (34, '4', '', '', 7);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (35, '5', '', '', 7);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (3, 'Jesus', 'lunes', 1, 1);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (4, 'Jesus', 'miercoles', 1, 1);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (5, 'Jesus', 'viernes', 1, 1);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (6, 'Angela', 'martes', 1, 5);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (7, 'Angela', 'jueves', 1, 5);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (8, 'Angela', 'sabado', 1, 5);